# conda env create -f environment.yml

name: web_scraping_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - requests-html=0.10.0
  - beautifulsoup4=4.11.1
  - requests=2.28.1
  - importlib_resources=5.10.0
  - fake-useragent=1.1.1
  - pip
  - pip:
    - lxml==4.9.2